# Neural Networks — Introduction & Structure

A **neural network** is a multilayered regression containing layers of **weights**, **biases**, and **nonlinear functions** (called *activation functions*) that sit between input and output variables.

**Deep learning** is a variant that uses multiple "hidden" (middle) layers of nodes.

Neural networks are optimized the same way as linear regression — using **stochastic gradient descent** to minimize residuals.

---

## When to Use Neural Networks

| Situation | Best Tool |
| --- | --- |
| Structured data (tables with rows & columns) | Linear/Logistic regression, Gradient boosted trees |
| Perceptual problems (images, audio, text) | Neural networks / Deep learning |

**Key idea:** Don't use a neural network when a simpler model works. Reserve them for *perceptual* tasks like image classification, speech recognition, and natural language processing.

### Variants of Neural Networks
- **Convolutional Neural Networks (CNNs):** Image recognition
- **Long Short-Term Memory (LSTM):** Time series / forecasting
- **Recurrent Neural Networks (RNNs):** Text-to-speech

---

## Example Problem — Light or Dark Font?

Given a background color (expressed as **RGB values** between 0–255), predict whether a **light (1)** or **dark (0)** font should be used.

- Dark background → light font
- Light background → dark font

We have **3 input variables**: Red, Green, Blue → and **1 output** (probability between 0 and 1).

If output ≥ 0.5 → light font, otherwise → dark font.

## Neural Network Structure

A simple neural network has **3 layers**:

```
Input Layer (3 nodes)  →  Hidden Layer (3 nodes)  →  Output Layer (1 node)
   R, G, B                  W·X + B (weighted sum)        Prediction (0 to 1)
```

### What happens at each node?

Each node in the hidden layer computes:

$$ Z = W_1 \cdot X_1 + W_2 \cdot X_2 + W_3 \cdot X_3 + B $$

This is just like a **linear function** (slope × input + intercept), but with multiple inputs.

Then the result passes through an **activation function** (we'll cover that in the next notebook).

### Weights & Biases — Think of Them Like This:
- **Weights (W)** = slopes (how much each input matters)
- **Biases (B)** = intercepts (shifts the function up/down)

These are analogous to `m` and `b` in `y = mx + b` from linear regression.

## Matrix Representation

We store weights as **matrices** and biases as **vectors**. This lets us use matrix multiplication to process everything at once.

- **Hidden layer weights** → 3×3 matrix (3 nodes × 3 inputs each)
- **Output layer weights** → 1×3 matrix (1 node × 3 inputs from hidden layer)
- **Hidden biases** → 3×1 vector (one bias per hidden node)
- **Output bias** → 1×1 vector (one bias for the output node)

Let's initialize them with random values:

In [1]:
import numpy as np

# Random weight matrices
w_hidden = np.random.rand(3, 3)   # 3 hidden nodes, each connected to 3 inputs
w_output = np.random.rand(1, 3)   # 1 output node, connected to 3 hidden nodes

# Random bias vectors
b_hidden = np.random.rand(3, 1)   # one bias per hidden node
b_output = np.random.rand(1, 1)   # one bias for output node

print("Hidden Weights (3x3):")
print(w_hidden)
print("\nOutput Weights (1x3):")
print(w_output)
print("\nHidden Biases:")
print(b_hidden)
print("\nOutput Bias:")
print(b_output)

Hidden Weights (3x3):
[[0.22719288 0.92496989 0.61596973]
 [0.85163314 0.96332833 0.310425  ]
 [0.51027354 0.2289196  0.73792724]]

Output Weights (1x3):
[[0.84739103 0.35705043 0.94465409]]

Hidden Biases:
[[0.9683    ]
 [0.80974836]
 [0.4180748 ]]

Output Bias:
[[0.1042302]]


### How to Read the Weight Matrix

```
W_hidden = [[W1, W2, W3],    ← Node 1 weights
            [W4, W5, W6],    ← Node 2 weights  
            [W7, W8, W9]]    ← Node 3 weights

W_output = [[W10, W11, W12]] ← Output node weights
```

Each **row** = one node. Each **column** = the weight for that input connection.

## Loading the Dataset

The dataset contains RGB values and whether a light (1) or dark (0) font is best.

We scale RGB values by dividing by 255 so they fall between 0 and 1 (this helps training).

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the dataset
all_data = pd.read_csv("https://tinyurl.com/y2qmhfsr")

# Show a few rows
print("Dataset shape:", all_data.shape)
print(all_data.head(10))

Dataset shape: (1345, 4)
   RED  GREEN  BLUE  LIGHT_OR_DARK_FONT_IND
0    0      0     0                       0
1    0      0   128                       0
2    0      0   139                       0
3    0      0   205                       0
4    0      0   238                       0
5    0      0   255                       0
6    0    100     0                       0
7    0    104   139                       0
8    0    128     0                       0
9    0    128   128                       0


In [3]:
# Extract inputs (R, G, B) and scale to 0-1
all_inputs = all_data.iloc[:, 0:3].values / 255.0
all_outputs = all_data.iloc[:, -1].values

# Split: 2/3 training, 1/3 testing
X_train, X_test, Y_train, Y_test = train_test_split(
    all_inputs, all_outputs, test_size=1/3
)

n = X_train.shape[0]  # number of training records
print(f"Training samples: {n}")
print(f"Testing samples: {X_test.shape[0]}")
print(f"\nClass distribution — 0 (dark): {sum(all_outputs == 0)}, 1 (light): {sum(all_outputs == 1)}")

Training samples: 896
Testing samples: 449

Class distribution — 0 (dark): 512, 1 (light): 833


## Key Takeaways

1. A neural network = input → hidden layer(s) → output
2. Each node computes: **weighted sum + bias**, then passes through an **activation function**
3. Weights & biases are like the `m` and `b` in linear regression, but there are many more of them
4. We represent weights as **matrices** and use **matrix multiplication** for efficiency
5. Use neural networks for perceptual problems (images, audio, text) — not for structured tabular data